### ISSUE TITLE
What are you comfortable teaching?

### ISSUE THREAD

**Issue by nhcooper123** [NHM-STARS/materials#1]
Day 1 ­ Data literacy
• A Efficient data collection principles.
• B Metadata ­ what is it and why is it important. 
• [Museum data collection exercise - done in groups of 4/5 with a curator].

Day 2 ­ Dealing with data
• A Introduction to R.
• B Data wrangling and tidying in R.
• C Data visualisation in R.
• D Basic data analysis in R (t tests, regressions etc).

Day 3 ­ Fundamentals of programming
• A Introduction to programming in R.
• B Introduction to tidy code and code review. 
• C Version control in Git and GitHub.

Day 4 ­ Reproducibility and Open Science
• A Reproducible report creation in R. 
• B Data archiving.
• C Code sharing.

**Comment by nhcooper123** [comment]
I'm most comfortable with: 2A-D and 3C and 4 B-C (because I have materials and have taught them before). Happy to do any of the others but would need to gather materials.

**Comment by annakrystalli** [comment]
Hi all. I have materials on github through RStudio (3C), intro to rmarkdown (4A) and RDM in ecology which covers parts like 1A-B, 2B, 4B.

**Comment by annakrystalli** [comment]
Hi guys, thought I'd add links to resources for an **RDM workshop** I gave last week to [ACCE DTP](https://acce.shef.ac.uk/) 1st-year postgrads.

Link to [html handouts](https://annakrystalli.github.io/ACCE_RDM/Rmd/index.html) and [Rmds on github](https://github.com/annakrystalli/ACCE_RDM/tree/master/Rmd)
