### ISSUE TITLE
Day 4 morning - git intro and GitHub with RStudio

### ISSUE THREAD

**Issue by nhcooper123** [NHM-STARS/materials#10]

**Comment by annakrystalli** [comment]
I'm basically going to adapt this material: https://github.com/annakrystalli/Mozfest_github-rstudio

**Comment by annakrystalli** [comment]
BTW are we going to do any standardisation of materials? ie any consistent theme / css for html and presentation outputs? @karthik ?

**Comment by karthik** [comment]
I think given the diversity of platforms (esp Windows machines) and experience, we are likely to have a lot of trouble with people getting Git installed.  This →  http://happygitwithr.com/installation-pain.html is a really comprehensive guide to getting people to deal with installation before they come. It is documented in great detail. I would vote for this to go into some pre-workshop guide.

**Comment by karthik** [comment]
re: standardization, I think for now we should not worry and just try to get a draft of all material in the repo first, and closer to the workshop we can have a quick chat about reformatting material.
