### ISSUE TITLE
Pre-course questionnaire and other pre course materials

### ISSUE THREAD

**Issue by nhcooper123** [NHM-STARS/materials#4]
I've made a start at this here: https://docs.google.com/forms/d/1oqasfbAkuvn-SWQVYcN7JUTXkQw8P7xXnaEHhsAfJq8/edit?usp=sharing

Feel free to add questions if you think I've missed something. I think we should plan to send this the the students at the start of May so they've a couple of weeks to get organised.

**Comment by nhcooper123** [comment]
Also a draft of what I was going to send to students beforehand

Hi all

We’re looking forward to meeting you all soon! Here are the things we’d like you to do before you come…please read carefully :)

**Pre course questions**
For us to get a feel for what you already know we’ve put together a short (anonymous) questionnaire. Please fill it in before you come. It also gives you chance to ask questions. Don’t panic – it isn’t a test, it’s just helpful for us to know where everyone is starting from.

**What to bring with you**
Ideally we want you to bring the laptop you’d normally do your analyses on. Everyone’s machine is different so it’s good to know stuff will work when you head home!  If you don’t have access to a laptop – no problem. Let me know asap and I’ll either get you a laptop or set up a Desktop machine for you. 

Notebook and pen!

Water bottle to reduce wasting plastic cups, and a reusable coffee/tea mug preferably with a lid (our caterers have cups but they are tiny so if you like a big mug of coffee bring one!)

Sense of humour and patience (it’s our first time running this course, so we may hit unforeseen problems!)

**What to install on your laptop** 
*Karthik to provide install scripts etc.*

Any problems with installing this let us know on the first day, or beforehand, so we can try and fix stuff before we get to that point in the course.

**Arrival on the first day**
Please meet me at 9.30am at the visitor desk. The visitor entrance is on Exhibition Road (it’s at the side of the Museum). It’s just before the public entrance, and has a big sign saying Flett Theatre and visitor entrance (it may be partially obscured by the public queue!). Inside you’ll see a security guard – tell him you are here for a course and he will let you through the door into the Museum. In front of you you’ll see the visitor desk. Just wait in that corner and I will come and collect you and give out passes.

On the other days do the exact same thing, but show the security guard your pass and then come straight up to the lower bridge room. **You’ll need to return your pass to me on the last day of the course.**

Those of you with NHM passes can go straight to the lower bridge room. If you don’t know where that is, come and meet us at the front visitor desk (near Sophie the stegosaurus).

**Course timetable**
We plan to start teaching each day at 9.30am and end at 5.30pm. Rough plan of action is attached, but we will keep this quite flexible in case some stuff takes longer/less time. Note that you will need to be out of the Museum by 5.45pm (or 7pm if a Museum staff member is with you).

Those of you commuting, please be aware that this was designed as a residential course, so there may be exercises you need to complete with your group in the evenings. Of course if you have caring responsibilities we completely understand that you may need to leave promptly. But it might be good to avoid making plans for the evenings that week. Nothing will take too long!

On the afternoon of Day 1 we will split you into groups of five and send you with a curator to a part of our collections to collect data to use for the rest of the week. You will then need to put this into a spreadsheet and collate metadata etc. so you can present this at the start of Day 2. You will work with this data for the rest of the week.

The course will end promptly at 5.30pm on Friday for those of you that need to make travel arrangements. 

**Evening activities**
*None of these activities are compulsory.*
Monday – Group trip to Imperial Student Bar to get to know the course attendees.
Wednesday/Thursday - *Something with RLadies or informal grouping of data folk*

**Food etc.**
The course will provide lunches, tea/coffee etc. Evening meals are not provided.

Those of you in the self catering accommodation could plan to cook food there. Or there are a number of reasonably priced options in the area. Gloucester Road and Earl’s Court are usually much cheaper than near South Kensington. Old Brompton road also has a few good falafel/kebab places. Ask your NHM colleagues for further advice! 

Pubs in the area tend to be overpriced (welcome to London!), but a couple of our favourites are The Queens Arms (near the Museum) and The Hereford Arms (near Gloucester Road). High Street Kensington is within walking distance and has some other options. 

We will also take you to the Imperial student bar on Monday evening – this has cheap beer and food (quality is not great!). You need to show your museum pass when they ask for your student ID. It can be busy there but great if the weather is good. Imperial also has another large student bar called East Side that I’m sure your NHM colleagues can direct you to. Either of these could be good places to work early in the evening.

**Comment by karthik** [comment]
Monday night is also LondonR where I'll be speaking.
